# Generated by Django 5.0.1 on 2024-01-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('is_completed', models.BooleanField()),
            ],
        ),
    ]
