# Generated by Django 5.0.1 on 2024-01-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_todo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='all_todo',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
