# Generated by Django 5.0.1 on 2024-01-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_all_todo_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_todo',
            old_name='deleted_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='all_todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
